# .pre-commit-config.yaml
default_stages: [pre-commit]
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args:
          - --tf-init-args=-upgrade
          - --hook-config=--retry-once-with-cleanup=true # requires jq - cleans up broken .terraform directories
      # - id: terraform_tflint
      #   args:
      #     - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      - id: terraform_trivy
        args:
          - --args=--skip-dirs=.terraform
      - id: terraform_checkov
        args:
          - --args=--quiet
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
      # - id: tfupdate
      #   name: Autoupdate Terraform Helm Provider
      #   args:
      #     - --args=provider helm
      #     - --args=--version "~> 2.0"
      # - id: tfupdate
      #   name: Autoupdate Terraform Kubernetes
      #     - --args=provider kubernetes
      #     - --args=--version "~> 2.0"
      # - id: tfupdate
      #   name: Autoupdate Terraform AWS Provider
      #     - --args=provider aws
      #     - --args=--version "~> 5.0"
      # - id: tfupdate
      #   name: Autoupdate Terraform Google Provider
      #     - --args=provider google
      #     - --args=--version "~> 5.0"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-merge-conflict
